apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-server-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: {{ .Values.volumeSize }}
